Feature: Prayer State Matrix - Comprehensive Date and Time Validation
  As a Muslim user
  I want to validate prayer states across different dates and times
  So that I can ensure accurate prayer tracking in all scenarios

  Background:
    Given the application is running
    Given I am logged in as a user with timezone "Asia/Kolkata" and created_at 2020-01-01 03:00

  @smoke @api @matrix @comprehensive
  Scenario Outline: Prayer state validation matrix
    Given I am checking the prayer times of "<date>" at time "<datetime>"
    # Prayer state checks
    Then the Fajr prayer should be in "<fajr_state>" state
    And the Dhuhr prayer should be in "<dhuhr_state>" state
    And the Asr prayer should be in "<asr_state>" state
    And the Maghrib prayer should be in "<maghrib_state>" state
    And the Isha prayer should be in "<isha_state>" state

    Examples: Prayer States Matrix
  | timezone     | date       | datetime         | fajr_state | dhuhr_state | asr_state | maghrib_state | isha_state | fajr_completed | fajr_can_complete | fajr_is_missed | fajr_can_mark_qada | fajr_is_late | fajr_prayer_status | fajr_status_color | fajr_status_text | dhuhr_completed | dhuhr_can_complete | dhuhr_is_missed | dhuhr_can_mark_qada | dhuhr_is_late | dhuhr_prayer_status | dhuhr_status_color | dhuhr_status_text | asr_completed | asr_can_complete | asr_is_missed | asr_can_mark_qada | asr_is_late | asr_prayer_status | asr_status_color | asr_status_text | maghrib_completed | maghrib_can_complete | maghrib_is_missed | maghrib_can_mark_qada | maghrib_is_late | maghrib_prayer_status | maghrib_status_color | maghrib_status_text | isha_completed | isha_can_complete | isha_is_missed | isha_can_mark_qada | isha_is_late | isha_prayer_status | isha_status_color | isha_status_text |
  # Summer Solstice (Longest Day) - June 21, 2025
  | Asia/Kolkata | 2025-06-21 | 2025-06-20 04:30 | future     | future      | future    | future        | future     | false          | false             | false          | false              | false        | future             | gray              | future         | false           | false              | false           | false               | false          | future             | gray               | future          | false          | false             | false          | false              | false        | future             | gray              | future        | false             | false                 | false               | false                 | false             | future                | gray                  | future            | false          | false              | false           | false              | false        | future             | gray              | future        |
  | Asia/Kolkata | 2025-06-21 | 2025-06-21 05:00 | ongoing    | future      | future    | future        | future     | false          | true              | false          | false              | false        | ongoing            | blue              | Ongoing          | false           | false              | false           | false               | false          | future             | gray               | future          | false          | false             | false          | false              | false        | future             | gray              | future        | false             | false                 | false               | false                 | false             | future                | gray                  | future            | false          | false              | false           | false              | false        | future             | gray              | future        |
  | Asia/Kolkata | 2025-06-21 | 2025-06-21 07:00 | missed     | future      | future    | future        | future     | false          | true              | true           | true               | true         | missed             | red               | Missed           | false           | false              | false           | false               | false          | future             | gray               | future          | false          | false             | false          | false              | false        | future             | gray              | future        | false             | false                 | false               | false                 | false             | future                | gray                  | future            | false          | false              | false           | false              | false        | future             | gray              | future        |
  | Asia/Kolkata | 2025-06-21 | 2025-06-21 13:00 | missed     | ongoing     | future    | future        | future     | false          | true              | true           | true               | true         | missed             | red               | Missed           | false           | true               | false           | false               | false          | ongoing            | blue               | Ongoing           | false          | false             | false          | false              | false        | future             | gray              | future        | false             | false                 | false               | false                 | false             | future                | gray                  | future            | false          | false              | false           | false              | false        | future             | gray              | future        |
  | Asia/Kolkata | 2025-06-21 | 2025-06-21 14:00 | missed     | ongoing     | future    | future        | future     | false          | true              | true           | true               | true         | missed             | red               | Missed           | false           | true               | false           | false               | false          | ongoing            | blue               | Ongoing           | false          | false             | false          | false              | false        | future             | gray              | future        | false             | false                 | false               | false                 | false             | future                | gray                  | future            | false          | false              | false           | false              | false        | future             | gray              | future        |
  | Asia/Kolkata | 2025-06-21 | 2025-06-21 16:00 | missed     | missed      | ongoing   | future        | future     | false          | true              | true           | true               | true         | missed             | red               | Missed           | false           | true               | true            | true                | true           | missed             | red                | Missed            | false          | true              | false          | false              | false        | ongoing            | blue              | Ongoing         | false             | false                 | false               | false                 | false             | future                | gray                  | future            | false          | false              | false           | false              | false        | future             | gray              | future        |
  | Asia/Kolkata | 2025-06-21 | 2025-06-21 17:00 | missed     | missed      | ongoing   | future        | future     | false          | true              | true           | true               | true         | missed             | red               | Missed           | false           | true               | true            | true                | true           | missed             | red                | Missed            | false          | true              | false          | false              | false        | ongoing            | blue              | Ongoing         | false             | false                 | false               | false                 | false             | future                | gray                  | future            | false          | false              | false           | false              | false        | future             | gray              | future        |
  | Asia/Kolkata | 2025-06-21 | 2025-06-21 18:00 | missed     | missed      | missed    | future        | future     | false          | true              | true           | true               | true         | missed             | red               | Missed           | false           | true               | true            | true                | true           | missed             | red                | Missed            | false          | true              | true           | true               | true         | missed             | red               | Missed          | false             | false                 | false               | false                 | false             | future                | gray                  | future            | false          | false              | false           | false              | false        | future             | gray              | future        |
  | Asia/Kolkata | 2025-06-21 | 2025-06-21 19:00 | missed     | missed      | missed    | ongoing       | future     | false          | true              | true           | true               | true         | missed             | red               | Missed           | false           | true               | true            | true                | true           | missed             | red                | Missed            | false          | true              | true           | true               | true         | missed             | red               | Missed          | false             | true                  | false               | false                 | false             | ongoing               | blue                  | Ongoing             | false          | false              | false           | false              | false        | future             | gray              | future        |
  | Asia/Kolkata | 2025-06-21 | 2025-06-21 20:00 | missed     | missed      | missed    | missed        | ongoing    | false          | true              | true           | true               | true         | missed             | red               | Missed           | false           | true               | true            | true                | true           | missed             | red                | Missed            | false          | true              | true           | true               | true         | missed             | red               | Missed          | false             | true                  | true                | true                  | true              | missed                | red                   | Missed              | false          | true               | false           | false              | false        | ongoing            | blue              | Ongoing         |
  | Asia/Kolkata | 2025-06-21 | 2025-06-21 21:00 | missed     | missed      | missed    | missed        | ongoing    | false          | true              | true           | true               | true         | missed             | red               | Missed           | false           | true               | true            | true                | true           | missed             | red                | Missed            | false          | true              | true           | true               | true         | missed             | red               | Missed          | false             | true                  | true                | true                  | true              | missed                | red                   | Missed              | false          | true               | false           | false              | false        | ongoing            | blue              | Ongoing         |
  | Asia/Kolkata | 2025-06-21 | 2025-06-21 22:00 | missed     | missed      | missed    | missed        | ongoing    | false          | true              | true           | true               | true         | missed             | red               | Missed           | false           | true               | true            | true                | true           | missed             | red                | Missed            | false          | true              | true           | true               | true         | missed             | red               | Missed          | false             | true                  | true                | true                  | true              | missed                | red                   | Missed              | false          | true               | false           | false              | false        | ongoing            | blue              | Ongoing         |
  | Asia/Kolkata | 2025-06-21 | 2025-06-21 23:00 | missed     | missed      | missed    | missed        | ongoing    | false          | true              | true           | true               | true         | missed             | red               | Missed           | false           | true               | true            | true                | true           | missed             | red                | Missed            | false          | true              | true           | true               | true         | missed             | red               | Missed          | false             | true                  | true                | true                  | true              | missed                | red                   | Missed              | false          | true               | false           | false              | false        | ongoing            | blue              | Ongoing         |
  | Asia/Kolkata | 2025-06-21 | 2025-06-22 00:00 | missed     | missed      | missed    | missed        | ongoing    | false          | true              | true           | true               | true         | missed             | red               | Missed           | false           | true               | true            | true                | true           | missed             | red                | Missed            | false          | true              | true           | true               | true         | missed             | red               | Missed          | false             | true                  | true                | true                  | true              | missed                | red                   | Missed              | false          | true               | false           | false              | false        | ongoing            | blue              | Ongoing         |
  | Asia/Kolkata | 2025-06-21 | 2025-06-22 01:00 | missed     | missed      | missed    | missed        | ongoing    | false          | true              | true           | true               | true         | missed             | red               | Missed           | false           | true               | true            | true                | true           | missed             | red                | Missed            | false          | true              | true           | true               | true         | missed             | red               | Missed          | false             | true                  | true                | true                  | true              | missed                | red                   | Missed              | false          | true               | false           | false              | false        | ongoing            | blue              | Ongoing         |
  | Asia/Kolkata | 2025-06-21 | 2025-06-22 02:00 | missed     | missed      | missed    | missed        | ongoing    | false          | true              | true           | true               | true         | missed             | red               | Missed           | false           | true               | true            | true                | true           | missed             | red                | Missed            | false          | true              | true           | true               | true         | missed             | red               | Missed          | false             | true                  | true                | true                  | true              | missed                | red                   | Missed              | false          | true               | false           | false              | false        | ongoing            | blue              | Ongoing         |
  | Asia/Kolkata | 2025-06-21 | 2025-06-22 03:00 | missed     | missed      | missed    | missed        | ongoing    | false          | true              | true           | true               | true         | missed             | red               | Missed           | false           | true               | true            | true                | true           | missed             | red                | Missed            | false          | true              | true           | true               | true         | missed             | red               | Missed          | false             | true                  | true                | true                  | true              | missed                | red                   | Missed              | false          | true               | false           | false              | false        | ongoing            | blue              | Ongoing         |
  | Asia/Kolkata | 2025-06-21 | 2025-06-22 04:00 | missed     | missed      | missed    | missed        | missed    | false          | true              | true           | true               | true         | missed             | red               | Missed           | false           | true               | true            | true                | true           | missed             | red                | Missed            | false          | true              | true           | true               | true         | missed             | red               | Missed          | false             | true                  | true                | true                  | true              | missed                | red                   | Missed              | false          | true               | true           | true              | true        | missed            | red              | missed         |